package View;


import Controller.Controller_Tamu;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MohamadEsa
 */
public class MainProgram extends javax.swing.JFrame {

  /**
   * Creates new form MainProgram
   */
  Controller_Tamu control;
  
  public MainProgram() {
    initComponents();
    control = new Controller_Tamu(this);
    this.setLocationRelativeTo(null);
    this.setTitle("Buku Tamu Virtual");
    setExtendedState(MAXIMIZED_BOTH);
    config();
  }
  
  public void tambahTanggal(){
    Date tgl = new Date();
        DateFormat daf = new SimpleDateFormat("EEEE, dd MMMMM yyyy");
        DateFormat tim = new SimpleDateFormat("HH:mm:ss");
        txtTglMasuk.setText(daf.format(tgl));
        txtWktMasuk.setText(tim.format(tgl));
  }
  
  public void ubahTanggal(){
    Date tgl = new Date();
        DateFormat tim = new SimpleDateFormat("HH:mm:ss");
        txtWktKeluar.setText(tim.format(tgl));
  }
  
  public void reset(){
    txtID.setText("ID");
    txtNama.setEnabled(false);
    txtAlamat.setEnabled(false);
    txtTelepon.setEnabled(false);
    txtTujuan.setEnabled(false);
    txtTglMasuk.setEnabled(false);
    txtWktMasuk.setEnabled(false);
    txtWktKeluar.setEnabled(false);
    
    btnAdd.setEnabled(true);
    btnHapus.setEnabled(false);
    btnProses.setEnabled(false);
    btnUbah.setEnabled(false);
    
    txtNama.setText("");
    txtAlamat.setText("");
    txtTelepon.setText("");
    txtTujuan.setText("");
    txtTglMasuk.setText("");
    txtWktMasuk.setText("");
    txtWktKeluar.setText("");
    txtCari.setText("Cari Sesuatu . . .");
  }
  
  public void baru(){
    txtNama.setEnabled(true);
    txtAlamat.setEnabled(true);
    txtTelepon.setEnabled(true);
    txtTujuan.setEnabled(true);
    txtTglMasuk.setEnabled(true);
    txtWktMasuk.setEnabled(true);
    txtWktKeluar.setEnabled(false);
    
    txtNama.setEditable(true);
    txtAlamat.setEditable(true);
    txtTelepon.setEditable(true);
    txtTujuan.setEditable(true);
    
    btnAdd.setEnabled(true);
    btnHapus.setEnabled(false);
    btnProses.setEnabled(true);
    btnUbah.setEnabled(false);
    
    tambahTanggal();
    txtNama.requestFocus();
  }
  
  public void config(){
    
    control.isiTabel();
  }

  public JTable getTableTamu() {
    return tableTamu;
  }

  public JTextArea getTxtAlamat() {
    return txtAlamat;
  }

  public JTextField getTxtCari() {
    return txtCari;
  }

  public JLabel getTxtID() {
    return txtID;
  }

  public JTextField getTxtNama() {
    return txtNama;
  }

  public JTextField getTxtTelepon() {
    return txtTelepon;
  }

  public JTextField getTxtTglMasuk() {
    return txtTglMasuk;
  }

  public JTextArea getTxtTujuan() {
    return txtTujuan;
  }

  public JTextField getTxtWktKeluar() {
    return txtWktKeluar;
  }

  public JTextField getTxtWktMasuk() {
    return txtWktMasuk;
  }

  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    btnAdd = new javax.swing.JButton();
    btnUbah = new javax.swing.JButton();
    btnHapus = new javax.swing.JButton();
    btnReset = new javax.swing.JButton();
    txtCari = new javax.swing.JTextField();
    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel3 = new javax.swing.JPanel();
    txtNama = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    txtAlamat = new javax.swing.JTextArea();
    jLabel3 = new javax.swing.JLabel();
    txtTelepon = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane4 = new javax.swing.JScrollPane();
    txtTujuan = new javax.swing.JTextArea();
    jLabel5 = new javax.swing.JLabel();
    txtTglMasuk = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txtWktMasuk = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    txtWktKeluar = new javax.swing.JTextField();
    txtID = new javax.swing.JLabel();
    btnProses = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tableTamu = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jScrollPane1.setBorder(null);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jPanel2.setBackground(new java.awt.Color(181, 215, 242));

    btnAdd.setBackground(new java.awt.Color(0, 123, 255));
    btnAdd.setText("BARU");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });

    btnUbah.setBackground(new java.awt.Color(255, 193, 7));
    btnUbah.setText("UBAH");
    btnUbah.setEnabled(false);
    btnUbah.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnUbahActionPerformed(evt);
      }
    });

    btnHapus.setBackground(new java.awt.Color(220, 53, 69));
    btnHapus.setText("HAPUS");
    btnHapus.setEnabled(false);
    btnHapus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHapusActionPerformed(evt);
      }
    });

    btnReset.setBackground(new java.awt.Color(108, 117, 125));
    btnReset.setText("RESET");
    btnReset.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnResetActionPerformed(evt);
      }
    });

    txtCari.setText("Cari Sesuatu . . .");
    txtCari.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtCariMouseClicked(evt);
      }
      public void mousePressed(java.awt.event.MouseEvent evt) {
        txtCariMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        txtCariMouseReleased(evt);
      }
    });
    txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        txtCariKeyReleased(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(txtCari)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(txtCari))
        .addContainerGap())
    );

    jSplitPane1.setDividerLocation(300);

    jPanel3.setBackground(new java.awt.Color(181, 215, 242));

    txtNama.setEnabled(false);

    jLabel1.setText("Nama Tamu");

    jLabel2.setText("Alamat");

    txtAlamat.setColumns(20);
    txtAlamat.setLineWrap(true);
    txtAlamat.setRows(5);
    txtAlamat.setWrapStyleWord(true);
    txtAlamat.setEnabled(false);
    jScrollPane3.setViewportView(txtAlamat);

    jLabel3.setText("Nomor Telepon");

    txtTelepon.setEnabled(false);

    jLabel4.setText("Tujuan Tamu");

    txtTujuan.setColumns(20);
    txtTujuan.setLineWrap(true);
    txtTujuan.setRows(5);
    txtTujuan.setWrapStyleWord(true);
    txtTujuan.setEnabled(false);
    jScrollPane4.setViewportView(txtTujuan);

    jLabel5.setText("Tanggal Masuk");

    txtTglMasuk.setEditable(false);
    txtTglMasuk.setEnabled(false);

    jLabel6.setText("Waktu Masuk");

    txtWktMasuk.setEditable(false);
    txtWktMasuk.setEnabled(false);

    jLabel7.setText("Waktu Keluar");

    txtWktKeluar.setEditable(false);
    txtWktKeluar.setEnabled(false);

    txtID.setText("ID");
    txtID.setEnabled(false);
    txtID.setFocusable(false);

    btnProses.setBackground(new java.awt.Color(39, 162, 67));
    btnProses.setText("PROSES");
    btnProses.setEnabled(false);
    btnProses.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnProsesActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
          .addComponent(txtTelepon)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btnProses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtNama)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtID)
              .addComponent(jLabel1)
              .addComponent(jLabel2)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel6)
              .addComponent(jLabel7)
              .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtTglMasuk)
              .addComponent(txtWktKeluar)
              .addComponent(txtWktMasuk))))
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(9, 9, 9)
        .addComponent(txtID)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtTglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtWktMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtWktKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jSplitPane1.setLeftComponent(jPanel3);

    tableTamu.setAutoCreateRowSorter(true);
    tableTamu.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tableTamu.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
    tableTamu.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableTamuMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tableTamu);

    jSplitPane1.setRightComponent(jScrollPane2);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSplitPane1)
        .addContainerGap())
    );

    jScrollPane1.setViewportView(jPanel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariMouseClicked
    txtCari.setText("");
    txtCari.requestFocus();
  }//GEN-LAST:event_txtCariMouseClicked

  private void txtCariMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariMousePressed
    
  }//GEN-LAST:event_txtCariMousePressed

  private void txtCariMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariMouseReleased

  }//GEN-LAST:event_txtCariMouseReleased

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    baru();
  }//GEN-LAST:event_btnAddActionPerformed

  private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
    if(txtNama.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Nama Tamu'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtAlamat.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Alamat'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtTelepon.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'No. Telepon'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtTujuan.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Tujuan'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtTglMasuk.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Tanggal Masuk'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtWktMasuk.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Waktu Masuk'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else{
      control.insert(this);
      config();
      reset();
    }
  }//GEN-LAST:event_btnProsesActionPerformed

  private void tableTamuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTamuMouseClicked
    
    txtID.setText(tableTamu.getValueAt(tableTamu.getSelectedRow(), 0).toString());
    txtNama.setText(tableTamu.getValueAt(tableTamu.getSelectedRow(), 1).toString());
    txtAlamat.setText(tableTamu.getValueAt(tableTamu.getSelectedRow(), 2).toString());
    txtTelepon.setText(tableTamu.getValueAt(tableTamu.getSelectedRow(), 3).toString());
    txtTujuan.setText(tableTamu.getValueAt(tableTamu.getSelectedRow(), 4).toString());
    txtTglMasuk.setText(tableTamu.getValueAt(tableTamu.getSelectedRow(), 5).toString());
    txtWktMasuk.setText(tableTamu.getValueAt(tableTamu.getSelectedRow(), 6).toString());
    ubahTanggal();
    btnAdd.setEnabled(false);
    txtWktKeluar.setEnabled(true);
    txtWktMasuk.setEnabled(true);
    txtTglMasuk.setEnabled(true);
    
    txtNama.setEditable(false);
    txtAlamat.setEditable(false);
    txtTelepon.setEditable(false);
    txtTujuan.setEditable(false);
    
    txtNama.setEnabled(true);
    txtAlamat.setEnabled(true);
    txtTelepon.setEnabled(true);
    txtTujuan.setEnabled(true);
    btnUbah.setEnabled(true);
    btnHapus.setEnabled(true);
    btnProses.setEnabled(false);
  }//GEN-LAST:event_tableTamuMouseClicked

  private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    if(txtNama.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Nama Tamu'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtAlamat.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Alamat'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtTelepon.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'No. Telepon'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtTujuan.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Tujuan'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtTglMasuk.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Tanggal Masuk'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else if(txtWktMasuk.getText().trim().isEmpty()){
      JOptionPane.showMessageDialog(null, "Kolom 'Waktu Masuk'\nTidak Boleh Kosong","Perhatian",JOptionPane.WARNING_MESSAGE);
    } else{
      control.update(this);
      config();
      reset();
    }
  }//GEN-LAST:event_btnUbahActionPerformed

  private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    reset();
  }//GEN-LAST:event_btnResetActionPerformed

  private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
    control.search(this);
  }//GEN-LAST:event_txtCariKeyReleased

  private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    if (tableTamu.getSelectedRow()>=0){
            int dialogResult = JOptionPane.showConfirmDialog(this, "Yakin Ingin Menghapus Data Ini?","Peringatan",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_OPTION){
                String id = tableTamu.getValueAt(tableTamu.getSelectedRow(),0).toString();
                control.delete(id);
                config();
                reset();
            }
        } else{
            JOptionPane.showMessageDialog(this, "Pilih Data Pada Tabel Sebelum Hapus","Kesalahan",JOptionPane.WARNING_MESSAGE);
        }
  }//GEN-LAST:event_btnHapusActionPerformed
    
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainProgram().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnHapus;
  private javax.swing.JButton btnProses;
  private javax.swing.JButton btnReset;
  private javax.swing.JButton btnUbah;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTable tableTamu;
  private javax.swing.JTextArea txtAlamat;
  private javax.swing.JTextField txtCari;
  private javax.swing.JLabel txtID;
  private javax.swing.JTextField txtNama;
  private javax.swing.JTextField txtTelepon;
  private javax.swing.JTextField txtTglMasuk;
  private javax.swing.JTextArea txtTujuan;
  private javax.swing.JTextField txtWktKeluar;
  private javax.swing.JTextField txtWktMasuk;
  // End of variables declaration//GEN-END:variables
}
